[project]
name = "readme-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "jinja2>=3.1.6",
    "uvicorn>=0.38.0",
]
